### ISSUE TITLE
Default rejection numbers

### ISSUE THREAD

**Issue by PeterBloomfield** [andreaskiermeier/AcceptanceSampling#2]
Hi Andreas,

I suggest that the default for the rejection numbers r in double-sampling should be rep(c[2] + 1, 2) instead of NULL. In at least one text on acceptance sampling, double-sampling is described in precisely those terms.

For more-than-two samples, the default _could_ be generalized to rep(c[length(c)] + 1, length(c)), but it's less clear that it _should_ be. In this case, perhaps missing rejection numbers should be cause for failure.

Thoughts?

Peter

**Comment by andreaskiermeier** [comment]
Thanks Peter.
If I understand correctly, then for
- the second sampling stage, the rejection number r_2 = c_2 + 1, which is needed to force a decision, and
- the first stage we use the same rejection number, i.e. r_1 = c_2 + 1.

I think that's sensible approach. I got a feeling you've got some code ready to go? If so, go for it.

**Comment by PeterBloomfield** [comment]
OK, will do--leaving rejection numbers required for more than 2 samples, right?

Peter

**Comment by andreaskiermeier** [comment]
Yes, I think we can just have defaults for single and double sampling.

Thanks.

**Comment by PeterBloomfield** [comment]
OK--closing.
